### PR TITLE
Emotional interaction visualization tool

### PR DESCRIPTION
**Pull request by TannerSorensen**
# Overview
One overarching goal is to add functionality to set of API analysis tools that are available to clients using our API service. This pull request provides a visualization tool for evaluating the strength of emotional interaction between two speakers in an audio file. The methodology is to treat parameters of Hawkes point process models as features describing the emotional interaction.

# Testing
Generate a visualization for the sample file by running the Python script `demo_pproc.py` on the sample file `samples/scarface_1019343_frames.json`.

```bash
python3 demo_pproc.py samples/scarface_1019343_frames.json
```

The result should match the attached html page `temp.html` contained in archive `temp.zip`.
[temp.zip](https://github.com/behavioral-signals/best-api-analyze/files/3292009/temp.zip)

# Functionality

Functionalities of the visualization are the following:

Left panel:

- Color-coded emotion labels over time for each speaker in the API outputs.
- Ticks at the time-points of emotion change-points.
- Hovering over the time-series of a given speaker displays the emotion label assigned by the API to that speaker at the time-point, as well as the timestamp of nearby emotion change-points
- "Baseline intensity" values, indicating the overall intensity of the point process formed by emotion change-points.

Right panel:

Heatmap displaying the strength with which the emotion change-points of a given speaker ("influencer", x-axis) excites emotion change-points in another speaker ("target", y-axis). Red indicates the strength of influence. The diagonal from top left to bottom right indicates self-excitation. The off-diagonal elements indicate influence from one speaker to another.

### CODE REVIEW

**Comment by TannerSorensen** [comment]
Thanks for the feedback @tyiannak. 

I added to `requirements.txt` and committed the changes to branch `pproc`, but when I went to push to the remote server, I received the following error that prevented me from pushing.
```
remote: Resolving deltas: 100% (4/4), completed with 3 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/pproc.
remote: error: At least 1 approving review is required by reviewers with write access.
To https://github.com/behavioral-signals/best-api-analyze.git
 ! [remote rejected] pproc -> pproc (protected branch hook declined)
error: failed to push some refs to 'https://github.com/behavioral-signals/best-api-analyze.git'
```
Is this intended behavior?

I tried to disable protected status for branch `pproc` as per https://help.github.com/en/enterprise/2.15/admin/developer-workflow/configuring-protected-branches-and-required-status-checks, but I do not have access to the "Settings" tab under the repository name.

**Comment by TannerSorensen** [comment]
Remote server is now accepting the push to branch `pproc` and I have made the updates to `requirements.txt`. As long as this PR works for you @tyiannak, I believe we can merge branch `pproc` to `master`.

**Comment by tyiannak** [comment]
Sure one last think, could you please move pproc and involved py files in a separate subfolder as next week we will start adding more content for other use cases as well?

**Comment by TannerSorensen** [comment]
Okay. I moved them all to a new folder `interaction_modeling_tool`.

**Pull request merged**
